#%RAML 0.8
title: prode-api
version: 0.1
mediaType: application/json
baseUri: http://0.0.0.0:3000/api/v1

/status/ping:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "ok"
              }

/auth:
  /login:
    post:
      body:
        application/json:
          example: |
            {
              "username": "username",
              "password": "password"
            }
      responses:
        201:
          body:
            application/json:
              example: |
                {
                  "token": "jwt"
                }

/teams:
  get:
  post:

  /{teamId}:
    get:
    put:
    delete:

/users:
  get:
  post:

  /{userId}:
    get:
    put:
    delete:

    /leagues:
      get:

      /{leagueId}:
        post:
        delete:

    /bets:
      get:
      post:

      /{betId}:
        get:
        put:
        delete:

/leagues:
  get:
  post:

  /{leagueId}:
    get:
    put:
    delete:

    /users:
      get:

/tournaments:
  get:
  post:

  /{tournamentId}:
    get:
    put:
    delete:

    /stages:
      get:
      post:

      /{stageId}:
        get:
        put:
        delete:

        /match:
          get:
          post:

          /{matchId}:
            get:
            put:
            delete:
